<a href="https://colab.research.google.com/github/VicktorKu/nn_2022/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота №2

студента групи КН-31

Кульковця Віктора 

# Main


## Засвоєння поняття тензору, знати різні способи створення тензорів

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

# створення
tensor = tf.Variable([
                   [7, 10, 13, 15],
                   [8, 11, 16, 17],
                   [9, 10, 12, 13],
                  #  [3, 7, 11, 15]
])

print(tf.constant([
                   [7, 10, 13],
                   [8, 12, 16]
]))

print(tf.random.Generator.from_seed(42).normal(shape=(2,3)))

tf.Tensor(
[[ 7 10 13]
 [ 8 12 16]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]], shape=(2, 3), dtype=float32)


## Cтворити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)

In [2]:
tensor = tf.Variable([
                   [7, 10, 13, 15],
                   [8, 11, 16, 17],
                   [9, 10, 12, 13],
                  #  [3, 7, 11, 15]
])

# визначення властивостей
print(tensor.shape)
print(tf.rank(tensor))
print(tf.size(tensor))
print(tf.expand_dims(tensor, axis=-1))

(3, 4)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(
[[[ 7]
  [10]
  [13]
  [15]]

 [[ 8]
  [11]
  [16]
  [17]]

 [[ 9]
  [10]
  [12]
  [13]]], shape=(3, 4, 1), dtype=int32)


## Продемонструвати основні математичні операції над тензорами

In [3]:
tensor = tf.Variable([
                   [7, 10, 13, 15],
                   [8, 11, 16, 17],
                   [9, 10, 12, 13],
                  #  [3, 7, 11, 15]
])

# основні математичні операції
print(tensor+10)
print(tensor*10)
print(tensor@tf.reshape(tensor, shape=(4, 3)))

tf.Tensor(
[[17 20 23 25]
 [18 21 26 27]
 [19 20 22 23]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ 70 100 130 150]
 [ 80 110 160 170]
 [ 90 100 120 130]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[557 551 513]
 [647 644 590]
 [535 530 504]], shape=(3, 3), dtype=int32)


## Провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)

In [6]:
tensor = tf.Variable([
                   [7, 10, 13, 15],
                   [8, 11, 16, 17],
                   [9, 10, 12, 13],
                  #  [3, 7, 11, 15]
])

# CRUD операції над даними, reshape, інтеграція з np.array, pd.DataFrame
tf.compat.v1.assign(tensor[2], [3, 7, 11, 15])
print(tf.slice(tensor, [1, 0], [1, 4]))
print(tf.reshape(tensor, shape=(4, 3)))
print(tf.Variable(np.array([[2, 4], [6, 9]])))
print(tf.Variable(pd.DataFrame([[2, 4], [6, 9]])))

tf.Tensor([[ 8 11 16 17]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[ 7 10 13]
 [15  8 11]
 [16 17  3]
 [ 7 11 15]], shape=(4, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[2, 4],
       [6, 9]])>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[2, 4],
       [6, 9]])>


# Footer


На лабораторній роботі ми розглянули основи бібліотеки TensorFlow